### ISSUE TITLE
Состояния сенсоров на русском языке не отображаются

### ISSUE THREAD

**Issue by Spirituss** [yandex/pogoda-home-assistant#1]
Добрый день! 
Спасибо за реализацию новой интеграции! Надеюсь на дальнейшее развитие и совершенствование продукта, в т.ч. с добавлением данных "народного мониторинга", чего очень не хватает во всех погодных интеграциях.

Теперь о самой ошибке:
При настройках интеграции выбран язык RU - все равно отображение на английском:
<img width="342" alt="Снимок экрана 2024-09-12 в 14 18 23" src="https://github.com/user-attachments/assets/65ad7000-1fb6-47a5-90da-6c93fa1e9709">

**Comment by dimastark** [comment]
Спасибо! Исправим.

**Comment by baradetsky** [comment]
Да и сами названия сенсоров тоже бы на русском неплохо бы иметь)

**Comment by PavelChertkov** [comment]
> Да и сами названия сенсоров тоже бы на русском неплохо бы иметь)

@baradetsky, приветствую

Я считаю, что названия сенсоров выстапают в качестве источника данных. На уровне интеграции их лучше не пререводить. В то же время названия сенсоров легко настраиваютя в карточках вывода на фронте

**Comment by PavelChertkov** [comment]
> Теперь о самой ошибке: При настройках интеграции выбран язык RU - все равно отображение на английском

@Spirituss, привет!

Переводы состояний уже в работе

Всё сложнее для единиц измерений. Переводить единицы измерений в интеграциях не разрешается. Вот тут соответствующий комментарий контрибьютера Home Assistant: https://github.com/home-assistant/architecture/discussions/1056#discussioncomment-9067059
