### ISSUE TITLE
Добавление сенсора(ов), отображающего(их) количество совершённых запросов.

### ISSUE THREAD

**Issue by il77781** [yandex/pogoda-home-assistant#11]
В добавление к соображениям, изложенным здесь - https://github.com/yandex/pogoda-home-assistant/issues/5#issue-2522541187, предлагаю добавить сенсоры, позволяющие иметь представление о количестве совершённых запросов и соответствующих лимитах...
Например:
- `количество запросов, совершённых за день` / 30
- `количество запросов, совершённых за месяц` / 380

Понятно, что при установленных лимитах запросы в режиме "по умолчанию", видимо, должны происходить один раз в два часа... Соответственно, в том случае, если это действительно так и возможность настраивать частоту запросов нам не предоставят, на конец месяца лимит не будет полностью израсходован и, таким образом, сервис не будет отключен до начала следующего месяца... Возможно, именно в этом была идея разработчиков...
Но, всё же хочется чуть больше контроля... Залезать каждый раз в личный кабинет для проверки оставшегося количества запросов представляется крайне неудобным.

**Comment by PavelChertkov** [comment]
Привет!  В этом была идея, чтобы один ключ использовался в одном доме

**Comment by il77781** [comment]
@PavelChertkov, добрый день!
Тут, в целом то, видимо, никто и не против - как уж решили, видимо, Ваши маркетологи - так тому и быть... Они ведь сейчас правят миром... )

> Понятно, что при установленных лимитах запросы в режиме "по умолчанию", видимо, должны происходить один раз в два часа... Соответственно, в том случае, если это действительно так и возможность настраивать частоту запросов нам не предоставят, на конец месяца лимит не будет полностью израсходован и, таким образом, сервис не будет отключен до начала следующего месяца...

Если это действительно так, то, наверное, опять же, всех пользователей и это устроит... Хотя, например, в других интеграциях, предоставляющих погодные данные, интервал запросов как будто бы поменьше будет...
Но и с этим непреклонным маркетологическим решением можно жить... )

А вот по поводу таких сенсоров:

> * `количество запросов, совершённых за день` / 30
> * `количество запросов, совершённых за месяц` / 380

Эти данные ведь уже есть в личном кабинете... Но заходить туда, чтобы их проверить - ну не очень удобно...
Добавить их в интеграцию как сенсоры (ну, или, на крайний  случай, в атрибуты) - это какая-то сложная технологическая задача?

**Comment by PavelChertkov** [comment]
Имея только ключ получить счетчики нет возможности. Ключ только для доступа к погодному Апи Яндекса и счетчиков там нет.

Настройку частоты обращений пока добавлять не планируем. И если один ключ используется в одном доме, то счетчики не переполнятся.

Сейчас единственный способ получить статус ключа - это посмотреть в личном кабинете: https://yandex.ru/pogoda/b2b/console/smarthome

Возможно в будущем будет расширение возможностей, но пока оставляем так

**Comment by il77781** [comment]
@PavelChertkov, понял Вас...
Ну, что же, возможно, попробую решить этот вопрос как-то иначе... )

**Comment by Nikolay-Ch** [comment]
> Настройку частоты обращений пока добавлять не планируем. И если один ключ используется в одном доме, то счетчики не переполнятся.
А если две погоды при этом запрашивать? Нужно подключать второй ключ с другого аккаунта? Не забаните ли вы после этого доступ?
