### ISSUE TITLE
Максимальная/минимальная температура не всегда отображается при настройке карточки "Прогноз погоды"

### ISSUE THREAD

**Issue by il77781** [yandex/pogoda-home-assistant#12]
Вот такой небольшой баг (или фича):
В том случае, если я при настройке карточки "Прогноз погоды" выбираю опцию `Текущая погода и прогноз`, то ниже текущего значения температуры, по всей видимости, отображаются значения максимальной и минимальной температуры в течение суток (либо же это ещё какие-то другие значения, смысл которых я не понял):
![IMG_20240914_141953](https://github.com/user-attachments/assets/a44c86b7-e73c-4cfc-88f3-caa506617186)
Однако, если я выбираю опцию `Только текущая погода`, эти значения уже не отображаются:
![IMG_20240914_142327](https://github.com/user-attachments/assets/27a58144-d9ad-4438-a180-f98c72ddb453)
Подобное поведение наблюдается и при выборе другого провайдера погодных данных...
С одной стороны, это и понятно: я ведь сам выбрал типа **только текущую погоду**...
Но и всё же... А если мне не нужно видеть прогноз (карточка занимает слишком много места по высоте), но видеть максимум и минимум при сохранении всё той же небольшой высоты карточки было бы неплохо... Как быть?
В выпадающем списке `Дополнительная информация` нужных данных нет, как нет и сенсора с такими данными... Есть ли возможность здесь что-то исправить?

**Comment by PavelChertkov** [comment]
@il77781, привет

Это ограничение вывода стандартной погодной карточки: https://www.home-assistant.io/dashboards/weather-forecast/

простое решение - это найти и использовать другую погодную карточку

Но если нравится именнно эта карточка, то можно скрыть прогноз используя плагин 'card-mod 3'
'card-mod 3' плагин позволяет применять CSS стили к карточкам
плагин можно установить через HACS: https://github.com/thomasloven/lovelace-card-mod

После установки плагина:

- перезагружаем HA
- переходим в текстовый редактор карточки: 
![image](https://github.com/user-attachments/assets/55725ce3-de22-4fc4-aeb1-f7584f4a0d41)
- добавляем параметр 'card_mod':
![image](https://github.com/user-attachments/assets/e9a5ceb8-94e4-4004-bee7-5ad0f89d5f8a)

Ниже конфиг текстом, для примера:
`show_current: true
show_forecast: true
type: weather-forecast
entity: weather.yandex_pogoda
forecast_type: hourly
name: за окном
card_mod:
  style: |
    ha-card div.forecast {
      display: none !important;
    }`
