### ISSUE TITLE
Состояние Condition HomeAssistant не отображается

### ISSUE THREAD

**Issue by Spirituss** [yandex/pogoda-home-assistant#2]
Сенсор добавлен в ХА, но не показывает данные:
<img width="346" alt="Снимок экрана 2024-09-12 в 14 24 10" src="https://github.com/user-attachments/assets/eeccb285-a285-4ff6-8a76-c142c8531d74">

**Comment by dimastark** [comment]
Тут причина в том, что `Condition HomeAssistant` выключен по-умолчанию. При его включении в настройках, нужно дождаться следующего обновления данных, тогда информация появится.

**Comment by Spirituss** [comment]
@dimastark 
Редко происходят обновления, поэтому не дождался. Сенсор появился.
