### ISSUE TITLE
Как загрузить версию интеграцию из ветки main ?

### ISSUE THREAD

**Issue by dmitkam** [yandex/pogoda-home-assistant#20]
Как загрузить версию интеграцию из ветки main ? HACS показывает только релизы.
Так тоже не даёт:
action: update.install
target:
  entity_id: update.yandex_pogoda_update
data:
  version: main

**Comment by PavelChertkov** [comment]
Привет! 
Как вариант, можно загрузить вручную, для этого нужно:
1. Скачать исходный код из репозитория
2. Скопировать с заменой содержимое https://github.com/yandex/pogoda-home-assistant/tree/main/custom_components/yandex_pogoda в <Home Assistant>/config/custom_components/yandex_pogoda
3. Рестартануть Home Assistant

**Comment by dmitkam** [comment]
Спасибо. Попробую.

**Comment by dmitkam** [comment]
Копирование не подошло. Вызывает ошибку. (

**Comment by PavelChertkov** [comment]
еще один способ - это сделать форк репы:
- делаем форк
- удаляем вот эти две строчки: https://github.com/yandex/pogoda-home-assistant/blob/main/hacs.json#L4-L5
- указать форкнутый репо в качестве источника интеграциии в HACS
<img width="443" alt="image" src="https://github.com/user-attachments/assets/8466a55e-43c4-4148-a6c0-407dad007e83">

**Comment by dmitkam** [comment]
не получилось (

![image](https://github.com/user-attachments/assets/7153aad5-fd6e-444a-8de8-593eb7b25e02)

**Comment by PavelChertkov** [comment]
в данный момент доступна версия v0.0.3 https://github.com/yandex/pogoda-home-assistant/releases/tag/v0.0.3
на данный момент она включает в себя все последние изменения

попробуйте, интересно получится ли ее установить?

**Comment by dmitkam** [comment]
пре-релиз ? Поставил ещё вчера. Уже написал ишью по поводу формата атрибутов прогноза.
![Screenshot_2024-10-08-11-45-54-007_io homeassistant companion android](https://github.com/user-attachments/assets/9b5bff2a-ac36-4778-b98b-2a9e9f0119ea)

**Comment by PavelChertkov** [comment]
> не получилось (

возможно это из-за доменного имени, давайте попробуем вот так еще https://github.com/dmitkam/pogoda-home-assistant/pull/1

**Comment by dmitkam** [comment]
не получилось...
![image](https://github.com/user-attachments/assets/c12fab72-fef3-474e-93e9-8be1cc6da6ef)

**Comment by PavelChertkov** [comment]
> не получилось...

что-то багует
попробуйте мой форк подтянуть: https://github.com/PavelChertkov/fork-pogoda-home-assistant
если из моего подтянуть получится, тогда:
перезагрузить HA и подтянуть уже свой: https://github.com/dmitkam/pogoda-home-assistant

**Comment by dmitkam** [comment]
Ваш подтянулся.

**Comment by dmitkam** [comment]
Я думаю, что надо ишью закрывать. Ваши пре-релизы устраивают на 100%.
Большое спасибо за Вашу поддержку.
