### ISSUE TITLE
Просьба добавить сенсоры Pressure и Pressure in mmhg

### ISSUE THREAD

**Issue by Spirituss** [yandex/pogoda-home-assistant#21]
### В чем проблема?

Сейчас этих сенсоров нет, соответственно, в карточке погоды вместо давления прочерк. Для определения давления приходится какую-то еще интеграцию использовать, чтобы давление доставать.
Давление нужно не только в Паскалях, но и в мм/рт.ст. Многие именно к таким единицам привыкли, карточки погоды некоторые также умеют отображать в двух единицах.

### Какая версия Home Assistant используется?

2024.9.3

### Проверка ключа

- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) статус ключа "Активно"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) тариф ключа "Бесплатный"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) счетчик запросов ключа не равен нулю

**Comment by PavelChertkov** [comment]
В рамках бесплатного тарифа давление недоступно: https://yandex.ru/legal/apib2c_weather_agreement/

В данный момент добавлять не планируем, возможно в будущем
