### ISSUE TITLE
Просьба добавить сенсор "геомагнитный фон"

### ISSUE THREAD

**Issue by Spirituss** [yandex/pogoda-home-assistant#22]
### В чем проблема?

Было бы здорово, если бы также был сенсор "геомагнитный фон" - ед.изм. баллы, шкала - от 0 до 10.
Данные, например, есть в Лаборатории солнечной астрономии ИКИ РАН и ИСЗФ СО РАН (https://xras.ru/magnetic_storms.html) или на Гисметео - https://www.gismeteo.ru/weather-moscow-4368/gm/
Иконку можно пришить такую - mdi:magnet-on 

### Какая версия Home Assistant используется?

2024.9.3

### Проверка ключа

- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) статус ключа "Активно"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) тариф ключа "Бесплатный"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) счетчик запросов ключа не равен нулю

**Comment by PavelChertkov** [comment]
В рамках бесплатного тарифа "геомагнитный фон" недоступен: https://yandex.ru/legal/apib2c_weather_agreement/

В данный момент добавлять не планируем, возможно в будущем
