### ISSUE TITLE
Просьба добавить сенсор "влажность"

### ISSUE THREAD

**Issue by Spirituss** [yandex/pogoda-home-assistant#23]
### В чем проблема?

Один из ключевых показателей погоды на улице, стандартная карточка погоды его также отражает.

### Какая версия Home Assistant используется?

2024.9.3

### Проверка ключа

- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) статус ключа "Активно"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) тариф ключа "Бесплатный"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) счетчик запросов ключа не равен нулю

**Comment by PavelChertkov** [comment]
В рамках бесплатного тарифа "влажность" недоступна: https://yandex.ru/legal/apib2c_weather_agreement/

В данный момент добавлять не планируем, возможно в будущем

**Comment by Spirituss** [comment]
@PavelChertkov 
Прекрасно, что лихо закрыли все ишьюсы, ничего не добавляя в интеграцию. Повторюсь, в таком виде она не особо интересна. Вот, как выглядит "нормальная" интеграции погоды в ХА:
<img width="491" alt="Снимок экрана 2024-10-11 в 15 39 31" src="https://github.com/user-attachments/assets/f79b67a3-46f6-497c-9117-2d58b69d7fa3">

А вот, как выглядит Yandex Pogoda:
<img width="488" alt="Снимок экрана 2024-10-11 в 15 40 12" src="https://github.com/user-attachments/assets/b7b67072-b522-4560-bb22-ce4ece524871">

Судя по тому, что писать ишьюсы перестали, как и комментировать - народ выводы сделал и забил на интеграцию. Пусть те, кому за погоду охота платить, дальше едят кактус.
