### ISSUE TITLE
Просьба добавить сенсор "UV index" - индекс солнечной активности 

### ISSUE THREAD

**Issue by Spirituss** [yandex/pogoda-home-assistant#24]
### В чем проблема?

Ед. измерения - UV
Шкала - от 0 до 10
Спасибо!

### Какая версия Home Assistant используется?

2024.9.3

### Проверка ключа

- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) статус ключа "Активно"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) тариф ключа "Бесплатный"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) счетчик запросов ключа не равен нулю

**Comment by Nikolay-Ch** [comment]
Просто интересно, а почему закрываете задачи как "completed"? Есть же статус "Not Planned"...

**Comment by dimastark** [comment]
> Я, конечно, не оракул. Но с таким подходом интеграция изначально мертворожденная.

Она не мертворождённая, она официальная, а значит будет развиваться.

> Кому платно нужно то, что есть у других и в достатке?

https://yandex.ru/dev/weather/doc/ru/concepts/releases#fevral-2024-goda
Прямо сейчас API Погоды активно развивается: мы добиваемся feature-parity с альтернативными решениями, а также добавляем параметры, которых нет ни у кого.

> Собственно, и интеграция Yandex Weather рабочая со всеми этими пирожками уже есть.

Она использует старый бесплатный тариф, который уже нельзя получить.

> Кажется, вы не совсем еще понимаете смысл идеи Home Assistant.

Мы собирали опросы реальных пользователей Умных Домов, в том числе и пользователей Home Assistant. Первым шагом мы открыли тариф, который покрывает большую часть кейсов использования.

Следующие шаги будут как раз про то, чтобы собрать обратную связь, понять, чего не хватает, что мы можем дать и как сделать так, чтобы это можно было дать бесплатно (либо за разумную подписку).

На всё нужно время :)

**Comment by Spirituss** [comment]
> Следующие шаги будут как раз про то, чтобы собрать обратную связь, понять, чего не хватает, что мы можем дать и как сделать так, чтобы это можно было дать бесплатно (либо за разумную подписку).
> 
> На всё нужно время :)

Значит, будем подождать... )
