### ISSUE TITLE
Просьба изменить тип данных для значения сенсора wind_bearing

### ISSUE THREAD

**Issue by il77781** [yandex/pogoda-home-assistant#26]
### В чем проблема?

Добрый день.
Обнаружил ещё вот такую штуку:
Значение сенсора `sensor.yandex_pogoda_wind_bearing`, по всей видимости, представляет собой угол в градусах...
Однако, видимо, **значение это представлено строковым типом данных**... Косвенно об этом говорит и тот факт, что в атрибутах этого сенсора не назначена единица измерения...
Наверное, поэтому при указании в этой карточке https://github.com/aukedejong/lovelace-windrose-card этого сенсора для `wind_direction_entity` карточка не отображается корректно...
При использовании в этой карточке соответствующих сенсоров из других интеграций, предоставляющих погодные данные (и там значение этого сенсора представлено в виде числа и имеет единицу измерения), все отображается корректно.

Кроме того, при использовании стандартной карточки "Прогноз погоды" при выборе в выпадающем списке `Дополнительная информация` параметра `Порывы Ветра` почему-то на карточке отображается именно это значение wind_bearing (причём это происходит и для других интеграций. Похоже, что это ошибка в карточке, но тем не менее).

Прошу поменять тип данных для `sensor.yandex_pogoda_wind_bearing` и назначить ему единицу измерения.

### Какая версия Home Assistant используется?

2024.10.0

### Проверка ключа

- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) статус ключа "Активно"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) тариф ключа "Бесплатный"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) счетчик запросов ключа не равен нулю

### Приложите лог, если в логе есть сообщение об ошибке, trace либо что-нибудь полезное

```txt
Ошибок в логе нет...
Обратил внимание только тогда, когда карточку https://github.com/aukedejong/lovelace-windrose-card начал настраивать...
```

**Comment by PavelChertkov** [comment]
у меня не получилось настроить карточку https://github.com/aukedejong/lovelace-windrose-card 
однако я добавил единицы измерения для сенсора: https://github.com/yandex/pogoda-home-assistant/pull/27/files#diff-01122b2bb67f19527c17f9f10efdecc048cab3105498f37c1916752b5004f882R97

возможно это поможет, но точно утверждать не могу

**Comment by il77781** [comment]
@PavelChertkov, да, у меня тоже не заработало...
В консоли DevTools в Хроме вылезает вот это:
![1728345550715](https://github.com/user-attachments/assets/e0efcf7a-2a4e-473b-a96c-ece13583e14e)
Вот такое предположение:
Сейчас сенсор `sensor.yandex_pogoda_wind_bearing` отличается от сенсоров, которые корректно воспринимаются этой карточкой, тем, что у него еще отсутствует атрибут `state_class: measurement`.
Не знаю, может быть, просто добавления этого атрибута и не достаточно, может быть, этот класс (или что-то подобное) необходимо назначать где-то в другом месте... А, может быть, этот атрибут и сам добавляется при назначении соответствующего класса... 
Других предположений пока нет...

**Comment by PavelChertkov** [comment]
> @PavelChertkov, похоже, добавление строчки `state_class=SensorStateClass.MEASUREMENT,` для `ATTR_API_WIND_BEARING` в файле sensors.py решает проблему... Не прям совсем сразу, но всё заработало...

@il77781, привет
Я не понимаю, заработало на v0.0.3 ? Или сами пропатчили сенсор, добавили `state_class=SensorStateClass.MEASUREMENT,`? 

Дело в том, что я не добавлял state_class я добавил только единицы измерения https://github.com/yandex/pogoda-home-assistant/blob/main/custom_components/yandex_pogoda/sensor.py#L97

мне интересно, помогло ли это?

**Comment by il77781** [comment]
@PavelChertkov, изначально на версии 0.0.3 не заработало...
А потом я обнаружил это различие в атрибутах, нашел файл sensors.py и там добавил state_class...
Не знаю, можно ли так делать, но после этого всё заработало...
Вы, наверное, можете и у себя так же проверить...

**Comment by PavelChertkov** [comment]
@il77781, можно
Но нужно тогда и в релиз добавить
добавил: https://github.com/yandex/pogoda-home-assistant/pull/31/files#diff-01122b2bb67f19527c17f9f10efdecc048cab3105498f37c1916752b5004f882R99

спасибо за участие и помощь

**Comment by il77781** [comment]
@PavelChertkov, Вам спасибо за оперативность!
А как устанавливать то изменения? Через HACS пока доступен только вчерашний pre-release v0.0.3 (и в нём, конечно же, `state_class` отсутствует)...
Просто скачать новую версию файла и заменить?

И вот по этой проблемке не подскажите где искать?

> А вот по этому поводу, теперь, после того, как все переведено корректно, становится понятно, что в переводе самой карточки допущена ошибка: для `wind_bearing` как соответствие указано `Порывы Ветра`...
> Возможно, просто необходима правка Translations для этой карточки... Не подскажите, где искать Translations для стандартных карточек, "вшитых" в HA?

**Comment by PavelChertkov** [comment]
выкатил 

> А как устанавливать то изменения? Через HACS пока доступен только вчерашний pre-release v0.0.3 (и в нём, конечно же, `state_class` отсутствует)...
> Просто скачать новую версию файла и заменить?

добавил в v0.0.4 можно обновиться: https://github.com/yandex/pogoda-home-assistant/releases/tag/v0.0.4

**Comment by PavelChertkov** [comment]
> А вот по этому поводу, теперь, после того, как все переведено корректно, становится понятно, что в переводе самой карточки допущена ошибка: для `wind_bearing` как соответствие указано `Порывы Ветра`...
> Возможно, просто необходима правка Translations для этой карточки... Не подскажите, где искать Translations для стандартных карточек, "вшитых" в HA?

вижу, что эта проблема есть, но пока еще не смотрел пути решения
судя по [количеству открытых в HomeAssistant ишью реквестов](https://github.com/home-assistant/core/issues) ждать официального фикса будет долго

планирую посмотреть, может можно на уровне переводов интеграции подложить свой перевод, но не факт, что так можно

**Comment by il77781** [comment]
@PavelChertkov, спасибо, в v0.0.4 всё работает корректно! Теперь только остаётся надеяться, что когда-нибудь Ваши маркетологи решат добавить нам ещё каких-нибудь погодных параметров... )))

> судя по [количеству открытых в HomeAssistant ишью реквестов](https://github.com/home-assistant/core/issues) ждать официального фикса будет долго

Да да, там всё точно затянется...


> может можно на уровне переводов интеграции подложить свой перевод, но не факт, что так можно

Да, это было здорово... Знать бы только, где они лежат (если вообще это так организовано для стандартных карточек)...

**Comment by PavelChertkov** [comment]
попробовал добавить перевод для entity Weather в файл локализации интеграции https://github.com/yandex/pogoda-home-assistant/blob/main/custom_components/yandex_pogoda/translations/ru.json#L46

К сожалению переводы не подтягиваются, вероятно, для интеграций установлено ограничение и Home Assistant не хочет подтягивать переводы для Weather :(  https://developers.home-assistant.io/docs/internationalization/custom_integration

В целом, народ решает схожие проблемы с  помощью кастомных карточек либо темлейтов https://community.home-assistant.io/t/translation-of-a-weather-entity/687326

**Comment by il77781** [comment]
@PavelChertkov, как мне кажется, проблема немного в другом...
При выборе в выпадающем списке `Дополнительная информация` параметра `Порывы Ветра` в YAML для этой стандартной карточки Прогноз погоды отправляется строка `secondary_info_attribute: wind_bearing`...
Как по мне, это проблема вообще никак не связана с Вашей интеграцией и её, соответственно, не решить правкой файлов Вашей интеграции...
Мне кажется, что где-то "внутри" Home Assistant "зашито" вот это неправильное соответствие `wind_bearing` - `Порывы Ветра` (по аналогии с файлами Translations для кастомных интеграций)...
Я, к сожалению, пока что никак не смог никакого подобного файла найти, сколько не рылся... Но, как мне кажется, что-то подобное такому файлу локализации где-то должно всё-таки находиться... Иначе непонятно, откуда все другие переведенные слова (`Температура`, `Ощущаемая температура`, `Скорость ветра`, `Скорость порывов ветра` и т.д.) "подтягиваются", ведь в Вашем ru.json они отсутствуют, но всё же в настройках этой карточки они переведены...
Проблема, в целом, вообще и не проблема... Просто думал, что Вы знаете, где может храниться подобная локализация, чтобы её можно было исправить, не открывая issue то ли для Frontend, то для Core с неопределёнными сроками и вероятностью положительного решения вопроса...

**Comment by il77781** [comment]
@PavelChertkov, в любом случае, спасибо Вам за попытки!
