### ISSUE TITLE
Просьба вынести прогноз («два раза в день» и «ежечасный») в атрибуты.

### ISSUE THREAD

**Issue by dmitkam** [yandex/pogoda-home-assistant#29]
Просьба вынести прогноз («два раза в день» и «ежечасный») в атрибуты, по типу как было раньше:
...
forecast: 
- datetime: '2024-10-07T20:00:00+03:00'
  wind_bearing: 0
  native_wind_speed: 2.7
  native_apparent_temperature: 4
  native_temperature: 7
  condition: cloudy
  native_wind_gust_speed: 7
...

Было удобно для выборочной отправки в Телеграм и для информеров (esp+экран).

**Comment by il77781** [comment]
@dmitkam, так прогноз, по всей видимости, есть а атрибутах и сейчас, просто хранится в сжатом виде (атрибут `forecast_compressed`)...
[Спросил](https://github.com/yandex/pogoda-home-assistant/issues/10#issuecomment-2398244763) об этом разработчика...

**Comment by dmitkam** [comment]
Это я понял. А как перевести в удобоваримый, пока нет... ))

**Comment by il77781** [comment]
@dmitkam, вот, надеюсь, @PavelChertkov нам подскажет, что с этим можно сделать...

**Comment by PavelChertkov** [comment]
не знал, что эта фича так востребована
сейчас что-нибудь придумаю

**Comment by PavelChertkov** [comment]
добавлено в предрелизе v0.0.4: https://github.com/yandex/pogoda-home-assistant/releases/tag/v0.0.4
