### ISSUE TITLE
Получение API ключа на аккаунт, который уже использовал API погоды ранее.

### ISSUE THREAD

**Issue by avbor** [yandex/pogoda-home-assistant#3]
Спасибо за интеграцию, но ситуация с получением API-ключа достаточно печальная.
Уже достаточно давно существуют неофициальные компоненты для получения данных с Я.Погоды, и многие пользователи HA ими пользовались, подключая себе бесплатные тарифы с ограничением на кол-во запросов в день (Погода для сайта).
И теперь, после появления официального компонента (а это прекрасно), у нас просто нет возможности получить ключ для него.
А предлагаемый поддержкой вариант с регистрацией нового аккаунта выглядит крайне странным, с учетом того, что для регистрации требуется номер мобильного телефона. 
Мне, например, совершенно не хочется заводить себе новый номер только ради погоды в ХА...

Надеюсь у разроботчиков компонента есть возможность донести абсурдность этой ситуации до ответсвенных лиц. =)

**Comment by ArchelonU** [comment]
Абсолютно согласен. Имея дома несколько колонок с Алисой и оплаченную подписку Яндекс Плюс не иметь возможности получения погоды из-за активированного ранее тестового тарифа.

Причем в описании сказано, что для частного использования будут доступен только текущий день + следующий. По описанию это не похоже на тестовый тариф, что был использован.

**Comment by baradetsky** [comment]
Практически слово-в-слово написал им в поддержку про регистрацию аккаунта для апи..... Идиотизм)))
И самое смешное, что даже на полученный ключ апи на новом аккаунте все равно выходит ошибка, даже спустя полчаса-час времени ожидания.

Ау, Яндекс, вы там работать будете или как?
![2024-09-12_22-43-45](https://github.com/user-attachments/assets/1a233da3-398a-478b-9a5b-74618c0dfceb)

**Comment by dimastark** [comment]
> Практически слово-в-слово написал им в поддержку про регистрацию аккаунта для апи..... Идиотизм))) И самое смешное, что даже на полученный ключ апи на новом аккаунте все равно выходит ошибка, даже спустя полчаса-час времени ожидания.
> 
> Ау, Яндекс, вы там работать будете или как? ![2024-09-12_22-43-45](https://private-user-images.githubusercontent.com/96811123/366956603-1a233da3-398a-478b-9a5b-74618c0dfceb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjgzNzcsIm5iZiI6MTcyNjIyODA3NywicGF0aCI6Ii85NjgxMTEyMy8zNjY5NTY2MDMtMWEyMzNkYTMtMzk4YS00NzhiLTlhNWItNzQ2MThjMGRmY2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExNDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYjYzNjJjZTVjN2JjMjJjYTg2ZTVhN2U1Y2VlOTk4OTg0ZTA0ZjNhNzAwZGMwZjMwMzM0Nzk5Mzk1NmNlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z6Xs9KNGnbmQ7znQYX5wMIxn2Hpl4Hc5FT-GfPMvLJM)

Вы получили ключ для Бизнеса и коммерческого использования.
Ответил вам тут https://github.com/yandex/pogoda-home-assistant/issues/6#issuecomment-2348715030

**Comment by dimastark** [comment]
> Спасибо за интеграцию, но ситуация с получением API-ключа достаточно печальная. Уже достаточно давно существуют неофициальные компоненты для получения данных с Я.Погоды, и многие пользователи HA ими пользовались, подключая себе бесплатные тарифы с ограничением на кол-во запросов в день (Погода для сайта). И теперь, после появления официального компонента (а это прекрасно), у нас просто нет возможности получить ключ для него. А предлагаемый поддержкой вариант с регистрацией нового аккаунта выглядит крайне странным, с учетом того, что для регистрации требуется номер мобильного телефона. Мне, например, совершенно не хочется заводить себе новый номер только ради погоды в ХА...
> 
> Надеюсь у разроботчиков компонента есть возможность донести абсурдность этой ситуации до ответсвенных лиц. =)

Мы заинтересованы, чтобы люди переезжали со старого бесплатного тарифа (он в ближайшем будущем может быть закрыт в пользу нового).

Если нужна помощь или консультация, мы готовы помочь.

> Причем в описании сказано, что для частного использования будут доступен только текущий день + следующий. По описанию это не похоже на тестовый тариф, что был использован.

Да, действительно, тариф предусматривает меньше дней. Однако новый бесплатный тариф позволяет использовать API новой версии ([список изменений](https://yandex.ru/dev/weather/doc/ru/concepts/releases#fevral-2024-goda)).

**Comment by dimastark** [comment]
Рекомендованный способ – получить новый ключ в новом Кабинете Разработчика.

**Comment by avbor** [comment]
> Мы заинтересованы, чтобы люди переезжали со старого бесплатного тарифа (он в ближайшем будущем может быть закрыт в пользу нового).

 Ну вот и как переехать, если есть старый бесплатный тариф? Новый аккаунт не предлагать )


> Если нужна помощь или консультация, мы готовы помочь.

Ну поддержка ваша отморозилась...

**Comment by avbor** [comment]
Хотя с текущими ограничениями я пожалуй на старом посижу...

Вот я хочу знать погоду дома и на даче, со старыми 50 обращениями в день хоть как то можно жить на две локации, а с новым как? Кучу аккаунтов плодить? Бред же...

**Comment by dimastark** [comment]
> Хотя с текущими ограничениями я пожалуй на старом посижу...
> 
> Вот я хочу знать погоду дома и на даче, со старыми 50 обращениями в день хоть как то можно жить на две локации, а с новым как? Кучу аккаунтов плодить? Бред же...

Да, в соседнем issue спрашивали про кейс в несколько умных домов
https://github.com/yandex/pogoda-home-assistant/issues/5#issuecomment-2348738734

Подумаем над этим

**Comment by avbor** [comment]
> Подумаем над этим

Это хорошо.

А еще было бы хорошо, что бы вы подумали над тем, как перейти на новый тариф тем, кто сейчас на старом )

**Comment by dimastark** [comment]
> А еще было бы хорошо, что бы вы подумали над тем, как перейти на новый тариф тем, кто сейчас на старом )

А у нас нет выбора, обязательно подумаем :)

**Comment by avbor** [comment]
> А у нас нет выбора, обязательно подумаем :)

Ну как, подумали? Вижу, что не очень...

**Comment by dimastark** [comment]
Пишите в поддержку, рассмотрим ваш кейс индивидуально
