### ISSUE TITLE
Не работает ключ

### ISSUE THREAD

**Issue by kolokolovg** [yandex/pogoda-home-assistant#33]
### В чем проблема?

Не принимает ключ созданый по ссылке.
https://yandex.ru/pogoda/b2b/console/smarthome
Ждал полдня 

### Какая версия Home Assistant используется?

Core

### Проверка ключа

- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) статус ключа "Активно"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) тариф ключа "Бесплатный"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) счетчик запросов ключа не равен нулю

**Comment by kolokolovg** [comment]
![изображение](https://github.com/user-attachments/assets/36d52a22-03b2-4d8a-8d4e-2b67587a5122)

**Comment by kolokolovg** [comment]
2024-10-16 16:59:08.368 ERROR (MainThread) [custom_components.yandex_weather.updater] Could not get data from API: <ClientResponse(https://api.weather.yandex.ru/v2/informers?lat=xxx&lon=xx&lang=en_US) [403 Forbidden]>
<CIMultiDictProxy('Content-Encoding': 'gzip', 'Content-Length': '48', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Wed, 16 Oct 2024 13:59:08 GMT', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-Req-Id': '1729087148348429-11534738730087786901-pmuvlnllirnopq57-BAL')>

**Comment by kolokolovg** [comment]
при вызове напрямую курлом - ключ успешно работает

**Comment by dimastark** [comment]
Судя по тексту ошибки используется старый плагин
https://github.com/IATkachenko/HA-YandexWeather

Он не работает с ключами нового бесплатного тарифа

**Comment by kolokolovg** [comment]
Да я уже понял это))) потому и закрыл ишью
