### ISSUE TITLE
access denied for basic role

### ISSUE THREAD

**Issue by Banzay1989** [yandex/pogoda-home-assistant#36]
### В чем проблема?

Не загружаются данные

### Какая версия Home Assistant используется?

2024.12.2

### Проверка ключа

- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) статус ключа "Активно"
- [ ] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) тариф ключа "Бесплатный"
- [X] в [личном кабинете](https://yandex.ru/pogoda/b2b/console/smarthome) счетчик запросов ключа не равен нулю

### Приложите лог, если в логе есть сообщение об ошибке, trace либо что-нибудь полезное

```txt
Регистратор: custom_components.yandex_pogoda.updater
Источник: custom_components/yandex_pogoda/updater.py:376
интеграция: Яндекс.Погода (документация, проблемы)
Первое сообщение: 18:47:22 (1 сообщений)
Последнее сообщение: 18:47:22

Errors in weather API response: {'errors': [{'message': 'access denied for basic role', 'path': ['weatherByPoint', 'now', 'feelsLike']}, {'message': 'access denied for basic role', 'path': ['weatherByPoint', 'forecast', 'days', 6, 'hours', 7, 'feelsLike']}, {'message': 'access denied for basic role', 'path': ['weatherByPoint', 'forecast', 'days', 0, 'hours', 23, 'feelsLike']} и тд
```

### Дополнительная информация

![image](https://github.com/user-attachments/assets/1879cb41-d4f0-4559-b1bb-241b778679b8)
через Postman работает. 
Другую роль не получить.

**Comment by dimastark** [comment]
Судя по всему вы получили Тестовый период API для Бизнеса. Нужен именно бесплатный ключ.
Скажите, пожалуйста, ваш логин или первые 5 символов API ключа

**Comment by Banzay1989** [comment]
Возможно, но переходил по ссылке и там других не дают.
463646c4-

**Comment by sashaanohin** [comment]
Добрый день. И у меня такая ошибка. Все симптомы такие же.
1a2a64e2-

**Comment by dimastark** [comment]
Поправил тариф у ваших ключей, можно проверять @Banzay1989 @sashaanohin

**Comment by Banzay1989** [comment]
Спасибо.
Работает.
Если завтра друзья захотят себе погоду от яндекса в умный дом. Мне им что сказать? Регистрироваться и если ключ не "Бесплатный", то писать сюда?
Или это был временный сбой?

**Comment by sashaanohin** [comment]
Спасибо.
Работает.

**Comment by dimastark** [comment]
> Мне им что сказать?

Ключ для умного дома можно получиться на этом лендинге
https://yandex.ru/pogoda/b2b/smarthome

Обычно всё работает, но если ранее уже регистрировался тут, то ключ может быть не того тарифа
https://yandex.ru/pogoda/b2b/console/home
(портал для бизнесов)

Так что вывод такой, что "обычно всё работает, но если не работает – пишите в поддержку" (ну или на github)
