### ISSUE TITLE
Прогноз дождя будет ?

### ISSUE THREAD

**Issue by dmitkam** [yandex/pogoda-home-assistant#4]
Раньше использовал запрос
wget -q --user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36' https://yandex.ru/pogoda/city -O /dev/stdout | sed 's/>/>\n/g' | grep "maps-widget-fact__title" -A1 | tail -1 | sed 's/<\/p>//g'

**Comment by avbor** [comment]
(В HA можно [scrape](https://www.home-assistant.io/integrations/scrape/) использовать... :))

**Comment by alexanderznamensky** [comment]
К сожалению, scrape перестал работать после ввода яндексом капчи.....
Хотя, если у Вас работает, был бы крайне признателен, если поделитесь. 

А то через Яндекс.Станцию получать прогноз дождя - тот еще костыль )))

**Comment by avbor** [comment]
![image](https://github.com/user-attachments/assets/759dc9a8-283b-431a-8fe2-a8a0bad3eaf6)
![image](https://github.com/user-attachments/assets/c3a2298a-4b61-4d2a-be3e-2fad5f2a9864)


![image](https://github.com/user-attachments/assets/887187d1-2624-407b-993d-c90f0d913692)

**Comment by alexanderznamensky** [comment]
Спасибо большое! 
Скорее всего дело было в том, что я использовал немного другой URL: 
https://yandex.ru/pogoda/maps/nowcast?lat=    &lon=

**Comment by dimastark** [comment]
Осадки можно получить в сенсоре с Погодным состоянием (condition)
Доступные condition можно узнать в документации

https://yandex.ru/dev/weather/doc/ru/concepts/spectaql#definition-Condition

**Comment by dimastark** [comment]
> ![image](https://private-user-images.githubusercontent.com/32452033/366996512-759dc9a8-283b-431a-8fe2-a8a0bad3eaf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjc5ODIsIm5iZiI6MTcyNjIyNzY4MiwicGF0aCI6Ii8zMjQ1MjAzMy8zNjY5OTY1MTItNzU5ZGM5YTgtMjgzYi00MzFhLThmZTItYThhMGJhZDNlYWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExNDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMzgzODEyN2EzYjc2ZjJlMzNiYWJmZDJlZjJjOWNiMDgzYTRlZGNiMDI3M2ZjOGE5MWRmYTgzNjdmYmRiNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7YQIXpsT8Lte9KDNCIX0JUW_hni5AcMh94BLbTnHpAE) ![image](https://private-user-images.githubusercontent.com/32452033/366996541-c3a2298a-4b61-4d2a-be3e-2fad5f2a9864.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjc5ODIsIm5iZiI6MTcyNjIyNzY4MiwicGF0aCI6Ii8zMjQ1MjAzMy8zNjY5OTY1NDEtYzNhMjI5OGEtNGI2MS00ZDJhLWJlM2UtMmZhZDVmMmE5ODY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExNDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3Y2Q1ZjExN2NmYTQ3ODYzNjkwZjE2YTE4ZjEyYzI0MTk0M2MxOTgxMWY4MjhkY2NjNTc3YjE3ZGJlZDVkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0a_znfL1wAbKk_Th83zhuyhUNUZGKsGGgRZDCBnsMIg)
> 
> ![image](https://private-user-images.githubusercontent.com/32452033/366996998-887187d1-2624-407b-993d-c90f0d913692.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjc5ODIsIm5iZiI6MTcyNjIyNzY4MiwicGF0aCI6Ii8zMjQ1MjAzMy8zNjY5OTY5OTgtODg3MTg3ZDEtMjYyNC00MDdiLTk5M2QtYzkwZjBkOTEzNjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExNDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MmQ4NzMyODY2NDgzNDIwYmFlN2MyZjQ4YzUxZjY2MjY5YzViNjFmY2Y2MmZmZWU2NDI5OGNjYWQ4ZmQ2ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qXPQJ4IRRvTyMQUgTylc9zsYA2OrA9VzfPbLeIxF0x4)

Предупреждаю, что такой вариант может перестать работать в любое время.

**Comment by dimastark** [comment]
Предусмотренный вариант получать осадки в рамках этого плагина – сенсор `condition`

**Comment by buzzzzer** [comment]
> Предусмотренный вариант получать осадки в рамках этого плагина – сенсор `condition`

Как я понимаю, condition - это состояние на сейчас. У меня сенсор сейчас отдаёт "CLOUDY"
 А хотелось бы прогноз вперёд увидеть.

**Comment by alexanderznamensky** [comment]
> Осадки можно получить в сенсоре с Погодным состоянием (condition) Доступные condition можно узнать в документации
> 
> https://yandex.ru/dev/weather/doc/ru/concepts/spectaql#definition-Condition

Ну это СОВСЕМ не то, что хотелось бы получить. 
Речь-то про датчик со значением ПРОГНОЗА ОСАДКОВ. 
В данный момент в Москве, например: В ближайшие 2 часа осадков не ожидается.

Хотя, очевидно, что Яндекс уже начал ограничивать запросы:
![image](https://github.com/user-attachments/assets/c384efc1-b654-439b-9f9d-5e9485a430cf)

**Comment by Slovator** [comment]
Что-то у меня не получается через scrape прогноз погоды получить, пишет в статусе "неизвестно" ....... Вот мои настройки


![Снимок экрана (41)](https://github.com/user-attachments/assets/d9bbe118-5cfc-480d-9d9e-393788ef4c60)
![Снимок экрана (42)](https://github.com/user-attachments/assets/3e26b4bd-ce20-4dde-853a-8a295846933d)

**Comment by alexanderznamensky** [comment]
> Что-то у меня не получается через scrape прогноз погоды получить, пишет в статусе "неизвестно" ....... Вот мои настройки
> 
> ![Снимок экрана (41)](https://private-user-images.githubusercontent.com/37020916/368196032-d9bbe118-5cfc-480d-9d9e-393788ef4c60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODUwMDIsIm5iZiI6MTcyNjU4NDcwMiwicGF0aCI6Ii8zNzAyMDkxNi8zNjgxOTYwMzItZDliYmUxMTgtNWNmYy00ODBkLTlkOWUtMzkzNzg4ZWY0YzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE0NTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkOGVhODdiNzdiZjNlNzdmN2UwM2EyY2Y1OTBkMmM3OGI0YmJiNTk3ZTExNDVmOWIxM2QyMGY3NmUzYjZmYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q-P9_DYkG_IlkrEaXdzgzSjSwrUETJBSQ0sGgZbxg8o) ![Снимок экрана (42)](https://private-user-images.githubusercontent.com/37020916/368196042-3e26b4bd-ce20-4dde-853a-8a295846933d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODUwMDIsIm5iZiI6MTcyNjU4NDcwMiwicGF0aCI6Ii8zNzAyMDkxNi8zNjgxOTYwNDItM2UyNmI0YmQtY2UyMC00ZGRlLTg1M2EtOGEyOTU4NDY5MzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE0NTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyY2U1NTEwNjc5MWYxMGIyMmUxNjAxMjllZGEzNTU3NTA3OThjMDRmZDhjYTViMTQ0MWQyNDQyMWEzNWFmZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.61nkLGtf7cyrdEho-ONzeqoQ_dZD9BOrzykFlujuexM)

Если внимательно сравните ссылки (вашу и от Александра @avbor), то заметите, что слово "maps" - лишнее.
Ваш URL: https://yandex.ru/pogoda/maps/mogilev?lat=53.000000&lon=30.000000
Должно быть: https://yandex.ru/pogoda/mogilev?lat=53.000000&lon=30.000000

И еще для проверки можно в браузере ссылку проверить (по вашей будет вот это):
![image](https://github.com/user-attachments/assets/c1eb2e3b-2a2c-4c08-a6dc-57981d94d715)
а по правильной ссылке открывается страничка и можно посмотреть тег (p.maps-widget-fact__title):
![image](https://github.com/user-attachments/assets/f61fb192-bfac-418f-92ca-6e61d20a0bba)

**Comment by PavelChertkov** [comment]
> > Предусмотренный вариант получать осадки в рамках этого плагина – сенсор `condition`
> 
> Как я понимаю, condition - это состояние на сейчас. У меня сенсор сейчас отдаёт "CLOUDY" А хотелось бы прогноз вперёд увидеть.

Condition доступен в прогнозе [Weather->forecast->condition](https://www.home-assistant.io/integrations/weather/#action-weatherget_forecasts)

Однако в рамках бесплатного тарифа  "Вероятность осадков" недоступна: https://yandex.ru/legal/apib2c_weather_agreement/

В данный момент добавлять не планируем, возможно в будущем
