### ISSUE TITLE
Отсутствуют настройки частоты обращения к сервису

### ISSUE THREAD

**Issue by Spirituss** [yandex/pogoda-home-assistant#5]
API имеет ограничения на кол-во вызовов в сутки:
![photo_2024-09-12 17 15 20](https://github.com/user-attachments/assets/382c815c-8381-4fbd-ae3d-250590833e7c)

при этом отсутствуют настройки частоты в интеграции ХА, как это сделано во многих других интеграциях. Настройка принципиально нужна, т.к. в случае использования нескольких инстансов ХА лимит может быть быстро израсходован в течение дня.

**Comment by dimastark** [comment]
Да, действительно, сейчас такой вариант использования не предусмотрен. 1 ключ – 1 умный дом.
Забрали в команду, подумаем, что можно с этим сделать.

**Comment by Nikolay-Ch** [comment]
Да даже на один акк... хочется понимать, с какой частотой обновления происходят сейчас и как это можно увеличить-уменьшить...

**Comment by Spirituss** [comment]
@dimastark 
1) Два инстанс на один API нужны не для двух умных домов, а для резервирования. Один инстанс - основной, второй - резервный, подхватывает управлением умным домом в случае сбоя основного. Для системы, которой поручается управление умным домом, схема, по сути, обязательная.
2) Кроме 2 инстансов также, как минимум, 2 кейса, когда управление частотой обновления требуется:
  - Нужен текущий срез погоды с частым обновлением - в случае изменчивой погоды для многих важно точно знать, что сейчас на улице, а не что было полчаса назад.
  - Внутри одного умного дома нужна погода для разных локаций внутри большого города (в Москве в разных районах погода сильно отличается) или разных городов). Другого варианта настроить вторую локацию, кроме как добавить еще раз интеграцию, нет.
3) Уже есть интеграция Yandex Weather, в которой такая настройка реализована, и это удобно и нужно. Хотелось бы и здесь:
<img width="541" alt="Снимок экрана 2024-10-03 в 09 53 41" src="https://github.com/user-attachments/assets/149a3a1c-a3dc-47b0-994b-efa3478549e7">

**Comment by PavelChertkov** [comment]
Настройку частоты обращений пока добавлять не планируем. 

Как вариант, константа, которая управляет частотой обновлений находится тут: https://github.com/yandex/pogoda-home-assistant/blob/main/custom_components/yandex_pogoda/const.py#L21
после изменения необходимо рестартануть Home Assistant

@Spirituss для двух инстансов можно получить два ключа и использовать в интеграции
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/58095555-61ab-4f07-9f31-860dbe08c51c">
