### ISSUE TITLE
Интеграция не авторизуется по ключу

### ISSUE THREAD

**Issue by baradetsky** [yandex/pogoda-home-assistant#6]
Не проходит авторизацию ключ
Нужное время ждал, даже больше чем нужно 
![2024-09-12_22-43-45](https://github.com/user-attachments/assets/d9636a14-aa2c-4df8-abaa-00d87a716e78)

**Comment by BV-Labs** [comment]
Точно такая же проблема.
Не проходит авторизацию ключ.
Нужное время ждал, даже больше чем нужно. Сервер HomeAssistant перезагружал.

**Comment by FerrumLogic** [comment]
+1 к проблеме

**Comment by dimastark** [comment]
> Не проходит авторизацию ключ Нужное время ждал, даже больше чем нужно ![2024-09-12_22-43-45](https://private-user-images.githubusercontent.com/96811123/366962024-d9636a14-aa2c-4df8-abaa-00d87a716e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjY5NTAsIm5iZiI6MTcyNjIyNjY1MCwicGF0aCI6Ii85NjgxMTEyMy8zNjY5NjIwMjQtZDk2MzZhMTQtYWEyYy00ZGY4LWFiYWEtMDBkODdhNzE2ZTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExMjQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMTEzMWJjN2YxYmEwMTBhZjI1YWIyNDNiNjI0Nzg4YjlhMjNlM2U4YzNlMTI1MWNkNTBmYzEwYjI0MWQxYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MBxqLR0H3_42T3L9-g5hsTjRA7-KCy04fyrjEQS-aUc)

Новый плагин работает только с новыми ключами бесплатного тарифа. Вижу ваше обращение в поддержку, выглядит так, что вы получили ключ "Пробного периода" тарифов для бизнеса.

Такие ключи не работают с Home Assistant.

Перенастроил ваш ключ на нужный тариф, можно проверять в интерфейсе Кабинета Разработчика
https://yandex.ru/pogoda/b2b/console/smarthome

**Comment by dimastark** [comment]
> Точно такая же проблема. Не проходит авторизацию ключ. Нужное время ждал, даже больше чем нужно. Сервер HomeAssistant перезагружал. Причем в личном кабинете видно, что запросы идут.
> 
> ![API key](https://private-user-images.githubusercontent.com/76734702/367170236-256f5c61-3f60-4fb4-996d-07002fb6bf60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjc1NjIsIm5iZiI6MTcyNjIyNzI2MiwicGF0aCI6Ii83NjczNDcwMi8zNjcxNzAyMzYtMjU2ZjVjNjEtM2Y2MC00ZmI0LTk5NmQtMDcwMDJmYjZiZjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExMzQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYzVlYjk5NWVhMWM3ZmU4YjQyYmQ5MzAwZDlhMGY3OTEwNzE0M2FiMmU2NjBhYmU5ZDIxMmNkZTRiYWU3MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R3tE4ogkLH1Fxh2_B6Ws6lHbDxxo5EG-_QvNvMEencU)

В вашем случае проблема другая, но я пока не пойму, какая.

Может быть есть возможность приложить логи, как выглядят проблемы с авторизацией?

**Comment by BV-Labs** [comment]
> В вашем случае проблема другая, но я пока не пойму, какая.
> Может быть есть возможность приложить логи, как выглядят проблемы с авторизацией?

Регистратор: custom_components.yandex_weather.updater
Источник: helpers/update_coordinator.py:367
интеграция: Яндекс.Погода ([документация](https://github.com/IATkachenko/HA-YandexWeather/wiki), [проблемы](https://github.com/IATkachenko/HA-YandexWeather/issues))
Первое сообщение: 14:51:34 (3 сообщений)
Последнее сообщение: 14:52:07

Error requesting Yandex Weather updater data: (403, '{"message":"forbidden"}\n')

**Comment by dimastark** [comment]
> P.S. Я нахожусь в Приднестровье, может это ограничение по geoip?

Таким не занимаемся :) А можете, пожалуйста, проверить сейчас, воспроизводится ли проблема?

**Comment by BV-Labs** [comment]
Эта ошибка возникла в пользовательской интеграции.

Регистратор: custom_components.yandex_weather.updater
Источник: helpers/update_coordinator.py:367
интеграция: Яндекс.Погода (документация, проблемы)
Первое сообщение: 14:51:34 (7 сообщений)
Последнее сообщение: 15:01:57

Error requesting Yandex Weather updater data: (403, '{"message":"forbidden"}\n')

**Comment by BV-Labs** [comment]
Эта ошибка возникла в пользовательской интеграции.

Регистратор: custom_components.yandex_weather.updater
Источник: custom_components/yandex_weather/updater.py:305
интеграция: Яндекс.Погода (документация, проблемы)
Первое сообщение: 14:51:34 (7 сообщений)
Последнее сообщение: 15:01:57

Could not get data from API: <ClientResponse(https://api.weather.yandex.ru/v2/informers?lat=46.62189908403901&lon=29.91611480712891&lang=en_US) [403 Forbidden]> <CIMultiDictProxy('Content-Encoding': 'gzip', 'Content-Length': '48', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Fri, 13 Sep 2024 11:52:07 GMT', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-Req-Id': '1726228327148192-6697177863450012529-amyljftieqehv3pt-BAL')>
Could not get data from API: <ClientResponse(https://api.weather.yandex.ru/v2/informers?lat=46.62189908403901&lon=29.91611480712891&lang=en_US) [403 Forbidden]> <CIMultiDictProxy('Content-Encoding': 'gzip', 'Content-Length': '48', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Fri, 13 Sep 2024 12:01:31 GMT', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-Req-Id': '1726228891272264-5900190924563437071-pw6rz2lbucwmzsfi-BAL')>
Could not get data from API: <ClientResponse(https://api.weather.yandex.ru/v2/informers?lat=46.62189908403901&lon=29.91611480712891&lang=en_US) [403 Forbidden]> <CIMultiDictProxy('Content-Encoding': 'gzip', 'Content-Length': '48', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Fri, 13 Sep 2024 12:01:40 GMT', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-Req-Id': '1726228900085039-4759098517905402894-kgtab5yrncn35mim-BAL')>
Could not get data from API: <ClientResponse(https://api.weather.yandex.ru/v2/informers?lat=46.62189908403901&lon=29.91611480712891&lang=en_US) [403 Forbidden]> <CIMultiDictProxy('Content-Encoding': 'gzip', 'Content-Length': '48', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Fri, 13 Sep 2024 12:01:46 GMT', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-Req-Id': '1726228906377792-16620822761159105093-d4vjk44ty6bhe2nn-BAL')>
Could not get data from API: <ClientResponse(https://api.weather.yandex.ru/v2/informers?lat=46.62189908403901&lon=29.91611480712891&lang=en_US) [403 Forbidden]> <CIMultiDictProxy('Content-Encoding': 'gzip', 'Content-Length': '48', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Fri, 13 Sep 2024 12:01:57 GMT', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-Req-Id': '1726228917842101-4910066119005896080-g4uxddsyx6a6bm7b-BAL')>

**Comment by dimastark** [comment]
> Эта ошибка возникла в пользовательской интеграции.
> 
> Регистратор: custom_components.yandex_weather.updater Источник: custom_components/yandex_weather/updater.py:305 интеграция: Яндекс.Погода (документация, проблемы) Первое сообщение: 14:51:34 (7 сообщений) Последнее сообщение: 15:01:57
> 
> Could not get data from API: <ClientResponse(https://api.weather.yandex.ru/v2/informers?lat=46.62189908403901&lon=29.91611480712891&lang=en_US) [403 Forbidden]> <CIMultiDictProxy('Content-Encoding': 'gzip', 'Content-Length': '48', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Fri, 13 Sep 2024 11:52:07 GMT', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-Req-Id': '1726228327148192-6697177863450012529-amyljftieqehv3pt-BAL')> Could not get data from API: <ClientResponse(https://api.weather.yandex.ru/v2/informers?lat=46.62189908403901&lon=29.91611480712891&lang=en_US) [403 Forbidden]> <CIMultiDictProxy('Content-Encoding': 'gzip', 'Content-Length': '48', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Fri, 13 Sep 2024 12:01:31 GMT', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-Req-Id': '1726228891272264-5900190924563437071-pw6rz2lbucwmzsfi-BAL')> Could not get data from API: <ClientResponse(https://api.weather.yandex.ru/v2/informers?lat=46.62189908403901&lon=29.91611480712891&lang=en_US) [403 Forbidden]> <CIMultiDictProxy('Content-Encoding': 'gzip', 'Content-Length': '48', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Fri, 13 Sep 2024 12:01:40 GMT', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-Req-Id': '1726228900085039-4759098517905402894-kgtab5yrncn35mim-BAL')> Could not get data from API: <ClientResponse(https://api.weather.yandex.ru/v2/informers?lat=46.62189908403901&lon=29.91611480712891&lang=en_US) [403 Forbidden]> <CIMultiDictProxy('Content-Encoding': 'gzip', 'Content-Length': '48', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Fri, 13 Sep 2024 12:01:46 GMT', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-Req-Id': '1726228906377792-16620822761159105093-d4vjk44ty6bhe2nn-BAL')> Could not get data from API: <ClientResponse(https://api.weather.yandex.ru/v2/informers?lat=46.62189908403901&lon=29.91611480712891&lang=en_US) [403 Forbidden]> <CIMultiDictProxy('Content-Encoding': 'gzip', 'Content-Length': '48', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Fri, 13 Sep 2024 12:01:57 GMT', 'Vary': 'Accept-Encoding', 'X-Content-Type-Options': 'nosniff', 'X-Req-Id': '1726228917842101-4910066119005896080-g4uxddsyx6a6bm7b-BAL')>

Судя по ошибке вы пытаетесь использовать новый ключ в этом плагине
https://github.com/IATkachenko/HA-YandexWeather

В данный момент старый плагин не поддерживается в рамках нового бесплатного тарифа для умного дома.

**Comment by dimastark** [comment]
Судя по связным issue проблем с корректным подключением нет.

В комментариях выше три проблемы:
1. Использование нового плагина со старым ключом
2. Использование нового плагина с ключом для Бизнеса
3. Использование старого плагина с новым ключом

Если я не прав, переоткрывайте issue

**Comment by baradetsky** [comment]
> Перенастроил ваш ключ на нужный тариф, можно проверять в интерфейсе Кабинета Разработчика https://yandex.ru/pogoda/b2b/console/smarthome

мне бы перенастроить на аккаунте foxbearhome, именно он используется под умный дом

**Comment by dimastark** [comment]
Готово, перенастроил

**Comment by dimastark** [comment]
> При получении api ключа из бесплатных была только опция "тестовый на 7 дней".

Нужно использовать новый кабинет разработчика и новый бесплатный тариф
https://yandex.ru/pogoda/b2b/console/smarthome

**Comment by KamchatkaSS** [comment]
Добрый день. Аналогичная проблема с ключами. Прошу подсказать как сменить тарифы?
(Не проходит авторизацию ключ. Ключ активный. Сервер HomeAssistant перезагружал. Причем в личном кабинете видно, что запросы идут) Предполагаю, что тоже тариф 7 дней для бизнеса. А как переключить на тестовый непонятно.... 
![1](https://github.com/user-attachments/assets/1bd14a89-780c-4e54-9236-e34604cf0afe)

**Comment by dimastark** [comment]
Тестовый тариф не подходит к этому плагину. Это можно решить обратившись в поддержку.

**Comment by KamchatkaSS** [comment]
Спасибо за оперативный ответ. Написал в поддержку Яндекса. 
Но вроде шел по их же кнопкам, чтобы получить тариф для погоды.... А получил тариф не тот. Получается, что все кто получают сейчас ключи, получают данную проблему с неправильным автоматическим выбором тарифа.

**Comment by KamchatkaSS** [comment]
Для тех у кого возникла проблема с ключами из-за неправильного выбора тарифа. Решение яндекса - регистрируйте новый аккаунт и заново получайте api - название правильного тарифа - "Бесплатный". (для работы с HA). Если Ваш аккуант уже засветился в яндекс бизнесе, то выбрать нужный тариф не сможете.

**Comment by KamchatkaSS** [comment]
Добрался до HA. Проблема с авторизацией осталась - Тариф Бесплатный ключ новый. Активирован. Может кто-нибудь подсказать куда копать? 
"Не могу получить данные. Проверьте корректность API-ключа в кабинете разработчика и убедитесь что выбран тариф 'Погода для сайта'. Может потребоваться до 30 минут, чтобы изменения настроек ключа вступили в силу на стороне Яндекса."

**Comment by dimastark** [comment]
@PavelChertkov Помоги, пожалуйста, разобраться

**Comment by KamchatkaSS** [comment]
Что-то не так спрашиваю?

**Comment by dimastark** [comment]
Нет нет, всё так. Мы разбираемся с проблемой

**Comment by PavelChertkov** [comment]
> ![Снимок экрана 2024-11-07 203234](https://private-user-images.githubusercontent.com/187204706/384075030-99d008bf-2707-4382-9c65-dee158180bf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTkwOTgsIm5iZiI6MTczMTA1ODc5OCwicGF0aCI6Ii8xODcyMDQ3MDYvMzg0MDc1MDMwLTk5ZDAwOGJmLTI3MDctNDM4Mi05YzY1LWRlZTE1ODE4MGJmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQwOTM5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDYyMzViODk3ODg0YzFjYmUwYTgzZmY0ZDUxZTgwMzVhZWFiMzFkZWU5MGQ4NjMxMWQwNjg3NTY1MjZiYWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nCUjcawER6bylD6gH4wXQah_72gN_YTS_kuFRaQSlEc)
> 
> Снес Яндекс погоду. Перезагрузил. Поставил обратно. Перезагрузил. При вводе ключа "already_in_progress". И ничего не происходит

Привет, попробуйте выполнить следующие действия:
- сохраните погодный ключ в удобном месте
- зайдите в настройки интеграции: Настройки -> Устройства и Службы -> Яндекс.Погода
- в появившемся окне выполнть действия, как на скриншоте ниже:
<img width="1331" alt="image" src="https://github.com/user-attachments/assets/17987806-717b-44fd-8560-893be8fa4c0a">
- в итоге должны быть удалены все записи
- выполните перезагрузку Home Assistant
- снова нужно зайти в настройки интеграции
- Включите отладку и добавьте новую запись используя погодный ключ: 
<img width="679" alt="image" src="https://github.com/user-attachments/assets/2f615139-96c1-4c24-9008-0036b627c764">
- Выключите отладку. Home Assistant предложит скачать отладочный лог, сохраните его

Если проблема осталась, тогда, пожалуйста, перекиньте мне собранный отладочный лог.

Прошу, напишите, о результатах
Спасибо!

**Comment by KamchatkaSS** [comment]
Огромное спасибо. Смогу сделать где-то в 22:00. Сразу сообщу!

**Comment by KamchatkaSS** [comment]
Добрался немного раньше. Проблемка - у меня в интеграциях нет Yandex. Он здесь не появился. Через объекты есть Яндекс Update
![Снимок экрана 2024-11-08 174710](https://github.com/user-attachments/assets/99191983-eafd-4093-b9e8-b8a65c3efb7b)
![Снимок экрана 2024-11-08 174826](https://github.com/user-attachments/assets/07a8c746-56bf-4921-86d3-e1d6caabf071)

**Comment by PavelChertkov** [comment]
В интеграциях нет Yandex: тогда нужно проверить скачалась ли интеграция через HACS

Прикладваю видео, но в вашем случае порядок действий может немного отличаться. Например, если в HACS сразу будет видно yandex pogoda, тогда можно пропустить добавление репозитория и сразу нажать кнопку "скачать"

https://github.com/user-attachments/assets/0adc9c85-7d36-4c07-ae2b-815b2da00600

Прошу, напишите, получилось ли добавить Yandex Pogoda в интеграции Home Assistant?
Спасибо!

**Comment by KamchatkaSS** [comment]
Решил попробовать погоду через OpenWeather - аналогичная проблема. Даже и н
![Снимок экрана 2024-11-10 103013](https://github.com/user-attachments/assets/5d73f05f-e746-4499-80b7-1cd5b205f274)
е знаю куда теперь копать.

**Comment by KamchatkaSS** [comment]
Пр этом запросы идут. 
![Снимок экрана 2024-11-10 105620](https://github.com/user-attachments/assets/73b11403-4c5c-41a2-bbd1-7f236fcd9eef)

**Comment by PavelChertkov** [comment]
>  ![Снимок экрана 2024-11-10 102457](https://private-user-images.githubusercontent.com/187204706/384668107-2f285154-1e3b-4549-a1dd-d0213e501c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyOTc2NjMsIm5iZiI6MTczMTI5NzM2MywicGF0aCI6Ii8xODcyMDQ3MDYvMzg0NjY4MTA3LTJmMjg1MTU0LTFlM2ItNDU0OS1hMWRkLWQwMjEzZTUwMWM3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwMzU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTFkNWU4NjJhYjI1NTY5YWE1ZTdiZWUyYzUwMDViOGM2MDRlODBkNTE4NjhhZWJkOTBlZGUxYTVmNDJmNzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ay6I1J0JrlInPtNOvbB42WwsRYFcVpi6iqLMEC_VVnM) )

На скрине видно, что выбрана другая интеграция, необходимо выбрать именно Yandex Pogoda со значаком зонтика
<img width="967" alt="image" src="https://github.com/user-attachments/assets/68ed2877-6beb-4b88-8b4c-3ab03587aef9">

для добавления в HACS необходимо указать репозиторий: https://github.com/yandex/pogoda-home-assistant
<img width="410" alt="image" src="https://github.com/user-attachments/assets/9f5bd81d-1cd1-47e0-b415-066b5becefb8">

Скорее всего причина ошибки именно в этом

**Comment by KamchatkaSS** [comment]
Огромное СПАСИБО! Все заработало! (извиняюсь за невнимательность)

**Comment by Striker72rus** [comment]
> Тестовый тариф не подходит к этому плагину. Это можно решить обратившись в поддержку.

А мне поддержка сказала что она ничего не меняет по тарифу - создавайте новый аккаунт...
