### ISSUE TITLE
Добавить настройки единицы измерения скорости ветра...

### ISSUE THREAD

**Issue by Nikolay-Ch** [yandex/pogoda-home-assistant#7]
Сейчас мне приходит скорость ветра в километрах в час... Но общеупотребительная скорость ветра в метрах в секунду.

Можно сделать вывод или просто в метрах в секунду, как обычно передают в прогнозах или настройку...

Вот, что я имею ввиду:
![image](https://github.com/user-attachments/assets/089b06d2-c506-45d3-9a37-4b68789ef4df)

**Comment by vturekhanov** [comment]
Это в настройках сущности weather.* можно выставить самостоятельно.

**Comment by dimastark** [comment]
Да, должно меняться в настройках

**Comment by Nikolay-Ch** [comment]
Я понимаю, что можно выставить в настройках... Просто, почему нельзя сделать это сразу по-умолчанию?

**Comment by Nikolay-Ch** [comment]
> Да, должно меняться в настройках


Я понимаю, что можно выставить в настройках... Просто, почему нельзя сделать это сразу по-умолчанию?

**Comment by PavelChertkov** [comment]
> Скорее всего - надо просто добавить корректное дефолтное значение единицы измерения в шаблон сенсора "weather"

Шаблон сенсора менять не нужно, сенсор показывает измерения в метрах в секунду.

Что касается сущности weather, то разработчики Home Assistant запрещают интеграциям менять единицы измерения по умолчанию: https://github.com/home-assistant/core/blob/dev/homeassistant/components/weather/__init__.py#L424

Прикладываю ссылку на ПР: https://github.com/home-assistant/core/pull/73441
<img width="880" alt="image" src="https://github.com/user-attachments/assets/d705fe41-32bf-404e-bc98-92f6436cfec3">
