### ISSUE TITLE
Добавить еще один сенсор направления ветра в виде текстового перечисления (словаря)

### ISSUE THREAD

**Issue by Nikolay-Ch** [yandex/pogoda-home-assistant#8]
Можно еще добавить дополнительный сенсор, который будет показывать направление ветра в виде перечисления (ествественно локализованного) на восемь или шестнадцать румбов:
В кратком варианте: С, СВ, В, ЮВ, Ю, ЮЗ, З, СЗ
Или в полном: Север, Северо-восток...

На 16 румбов будет примерно так:
![image](https://github.com/user-attachments/assets/eeeac2f9-2927-4c46-bd81-ce7092d71d6d)

**Comment by dimastark** [comment]
Это градусы
